### ISSUE TITLE
Feature Request: Make the intro `pasteme-cli` installer command fancier

### ISSUE THREAD

**Issue by lnxpy** [collove/pasteme#49]
Give a glowing gradient-like background color to the installation div to make it much more special!

**Comment by mh-firouzjah** [comment]
Hi, I tried to give the parent element `div` a class name `glow` and then the following code worked for me. hope you enjoy it:
```css
<style>
    .glow pre{
        padding: 3px;
        border-radius: 15px;
    }
    .glow pre code {
        border-radius: 15px;
    }
    .glow {
  position: relative;
  border-radius: 15px;
  padding: 0 2px;
  margin: 2px;
}

.glow:before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  z-index: -1;
  width: 100%;
  height: 100%;
  background: white;
  filter: blur(5px); /* remove or reduce this amount if the shape is too blur */
  border-radius: 15px;
}

.glow:after {
  content: "";
  position: absolute;
  top: -2px;
  bottom: -2px;
  left: -2px;
  right: -2px;
  z-index: -2;
  /* take care of browser compatibility here for linear background */
  background: linear-gradient(45deg, #00ddff, #0800ff, #bf00ff, #ff0095, #ff0000);
  filter: blur(15px);
}

</style>
```
